### ISSUE TITLE
Сould not install on Mac OS Catalina

### ISSUE THREAD

**Issue by sashabeep** [foundation/node-foundation-customizer#16]
Full screen of errors, mainly due to permissions and so. Can't figure out how to install it.
Installation guide requires update

**Comment by DanielRuf** [comment]
Hi @sashabeep,

can you provide some more info like your NodeJS version?

**Comment by sashabeep** [comment]
v10.16.3
Xcode command line tooks installed as well
End of log file
```
12292 verbose stack Error: node-sass@4.5.3 postinstall: `node scripts/build.js`
12292 verbose stack Exit status 1
12292 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/no$
12292 verbose stack     at EventEmitter.emit (events.js:198:13)
12292 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/no$
12292 verbose stack     at ChildProcess.emit (events.js:198:13)
12292 verbose stack     at maybeClose (internal/child_process.js:982:16)
12292 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.$
12293 verbose pkgid node-sass@4.5.3
12294 verbose cwd /Users/sashabeep/node-foundation-customizer
12295 verbose Darwin 19.0.0
12296 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
12297 verbose node v10.16.3
12298 verbose npm  v6.9.0
12299 error code ELIFECYCLE
12300 error errno 1
12301 error node-sass@4.5.3 postinstall: `node scripts/build.js`
12301 error Exit status 1
12302 error Failed at the node-sass@4.5.3 postinstall script.
12302 error This is probably not a problem with npm. There is likely additional logging$
12303 verbose exit [ 1, true ]
```
screen output
![Снимок экрана 2019-10-21 в 17 32 40](https://user-images.githubusercontent.com/5689796/67214695-d91df880-f428-11e9-9c87-99d761b66315.png)

**Comment by DanielRuf** [comment]
You have to probably run `xcode-select --install`.

**Comment by sashabeep** [comment]
It's already installed

```
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by DanielRuf** [comment]
So Xcode is not installed / updated then?

**Comment by DanielRuf** [comment]
In general this is a node-gyp issue with missing build deps on your system, not this project =)

**Comment by sashabeep** [comment]
Xcode not installed, only command line tools. It was always enough...

**Comment by DanielRuf** [comment]
xcode CLI does not work without Xcode ;-)

**Comment by sashabeep** [comment]
> xcode CLI does not work without Xcode ;-)
No, it's wrong.

**Comment by DanielRuf** [comment]
Well, the terminal output says it =) And this is a node-gyp issue if it is one at all, not a foundation-* issue =)

**Comment by DanielRuf** [comment]
See https://github.com/nodejs/node-gyp/issues/569 and other relevant issues.

Closing as this is not an issue on our end and not specific to node-foundation-customizer.

**Comment by DanielRuf** [comment]
Also relevant:

https://github.com/schnerd/d3-scale-cluster/issues/7
https://github.com/tensorflow/tfjs/issues/372
...

**Comment by sashabeep** [comment]
```
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
```
node-sass 4.5.3 does not supported by node 10x https://github.com/sass/node-sass/issues/2672#issuecomment-493640504

**Comment by DanielRuf** [comment]
It will be built from source in this case.
See also https://github.com/sass/node-sass/issues/2672#issuecomment-493645314 where someone has 4.12.0 on 10.15.

I tried to install node-sass 4.5.3 on 10.16.3 on Mojave and it works:
```terminal
➜  node-sass-test yarn init -y
yarn init v1.19.0
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.04s.
➜  node-sass-test node --version
v10.16.3
➜  node-sass-test yarn add ode-sass@4.5.3
yarn add v1.19.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/ode-sass: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/danielruf/projects/node-sass-test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
➜  node-sass-test 
➜  node-sass-test yarn add node-sass@4.5.3
yarn add v1.19.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 152 new dependencies.
info Direct dependencies
└─ node-sass@4.5.3
info All dependencies
...
├─ node-sass@4.5.3
...
✨  Done in 146.23s.
➜  node-sass-test 
```

**Comment by DanielRuf** [comment]
It will be built from source in this case.

I tried to install node-sass 4.5.3 on 10.16.3 on Mojave and it works:
```terminal
➜  node-sass-test yarn init -y
yarn init v1.19.0
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.04s.
➜  node-sass-test node --version
v10.16.3
➜  node-sass-test yarn add ode-sass@4.5.3
yarn add v1.19.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/ode-sass: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/danielruf/projects/node-sass-test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
➜  node-sass-test 
➜  node-sass-test yarn add node-sass@4.5.3
yarn add v1.19.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 152 new dependencies.
info Direct dependencies
└─ node-sass@4.5.3
info All dependencies
...
├─ node-sass@4.5.3
...
✨  Done in 146.23s.
➜  node-sass-test 
```

**Comment by DanielRuf** [comment]
> npm ERR! Failed at the node-sass@4.5.3 postinstall script.

Please provide the whole console output as I can not reproduce this.

**Comment by DanielRuf** [comment]
It will be built from source in this case.

I tried to install node-sass 4.5.3 on 10.16.3 on Mojave and it works:
```terminal
➜  node-sass-test yarn init -y
yarn init v1.19.0
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.04s.
➜  node-sass-test node --version
v10.16.3
➜  node-sass-test yarn add node-sass@4.5.3
yarn add v1.19.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 152 new dependencies.
info Direct dependencies
└─ node-sass@4.5.3
info All dependencies
...
├─ node-sass@4.5.3
...
✨  Done in 146.23s.
➜  node-sass-test 
```

> npm ERR! Failed at the node-sass@4.5.3 postinstall script.

Please provide the whole console output as I can not reproduce this.

**Comment by DanielRuf** [comment]
Same for npm here:
```
➜  node-sass-test npm i
...
gyp info ok 
Installed to /Users/danielruf/projects/node-sass-test/node_modules/node-sass/vendor/darwin-x64-64/binding.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN node-sass-test@1.0.0 No description
npm WARN node-sass-test@1.0.0 No repository field.

added 176 packages from 139 contributors and audited 516 packages in 148.607s
found 0 vulnerabilities

➜  node-sass-test npm ls --depth=0
node-sass-test@1.0.0 /Users/danielruf/projects/node-sass-test
└── node-sass@4.5.3
```

**Comment by DanielRuf** [comment]
Same for npm here:
```terminal
➜  node-sass-test npm i
...
gyp info ok 
Installed to /Users/danielruf/projects/node-sass-test/node_modules/node-sass/vendor/darwin-x64-64/binding.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN node-sass-test@1.0.0 No description
npm WARN node-sass-test@1.0.0 No repository field.

added 176 packages from 139 contributors and audited 516 packages in 148.607s
found 0 vulnerabilities

➜  node-sass-test npm ls --depth=0
node-sass-test@1.0.0 /Users/danielruf/projects/node-sass-test
└── node-sass@4.5.3
```

**Comment by DanielRuf** [comment]
It will be built from source in this case.

I tried to install node-sass 4.5.3 on 10.16.3 on Mojave and it works:
```shell
➜  node-sass-test yarn init -y
yarn init v1.19.0
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.04s.
➜  node-sass-test node --version
v10.16.3
➜  node-sass-test yarn add node-sass@4.5.3
yarn add v1.19.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 152 new dependencies.
info Direct dependencies
└─ node-sass@4.5.3
info All dependencies
...
├─ node-sass@4.5.3
...
✨  Done in 146.23s.
➜  node-sass-test 
```

> npm ERR! Failed at the node-sass@4.5.3 postinstall script.

Please provide the whole console output as I can not reproduce this.

Same for npm here:
```shell
➜  node-sass-test npm i
...
gyp info ok 
Installed to /Users/danielruf/projects/node-sass-test/node_modules/node-sass/vendor/darwin-x64-64/binding.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN node-sass-test@1.0.0 No description
npm WARN node-sass-test@1.0.0 No repository field.

added 176 packages from 139 contributors and audited 516 packages in 148.607s
found 0 vulnerabilities

➜  node-sass-test npm ls --depth=0
node-sass-test@1.0.0 /Users/danielruf/projects/node-sass-test
└── node-sass@4.5.3
```

**Comment by DanielRuf** [comment]
It will be built from source in this case.

I tried to install node-sass 4.5.3 on 10.16.3 on Mojave and it works:
```shell
➜  node-sass-test yarn init -y
yarn init v1.19.0
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.04s.
➜  node-sass-test node --version
v10.16.3
➜  node-sass-test yarn add node-sass@4.5.3
yarn add v1.19.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 152 new dependencies.
info Direct dependencies
└─ node-sass@4.5.3
info All dependencies
...
├─ node-sass@4.5.3
...
✨  Done in 146.23s.
➜  node-sass-test 
```

Same for npm here:
```shell
➜  node-sass-test npm i
...
gyp info ok 
Installed to /Users/danielruf/projects/node-sass-test/node_modules/node-sass/vendor/darwin-x64-64/binding.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN node-sass-test@1.0.0 No description
npm WARN node-sass-test@1.0.0 No repository field.

added 176 packages from 139 contributors and audited 516 packages in 148.607s
found 0 vulnerabilities

➜  node-sass-test npm ls --depth=0
node-sass-test@1.0.0 /Users/danielruf/projects/node-sass-test
└── node-sass@4.5.3
```

> npm ERR! Failed at the node-sass@4.5.3 postinstall script.

Please provide the whole console output as I can not reproduce this.

**Comment by nfantone** [comment]
Same over here. I can confirm that installing xcode CLI _only_ has always been enough - but after upgrading to macOS Catalina, `node-gyp` started complaining about `gyp: No Xcode or CLT version detected!`.

```sh
❯ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

> yarn
[...]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node@10/10.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
```

**Comment by nfantone** [comment]
@DanielRuf 

> Well, the terminal output says it

Not really, no. The terminal output, if it is to be trusted, explicitly says that is looks for `DeveloperToolsCLILeo` and `DeveloperToolsCLI`. No need for a full XCode installation.

**Comment by Vishesh-Gupta** [comment]
Having the exact same issue after updating to the latest release on macOS Catalina. It was working completely fine before the improvements and stability release on the OS.

**Comment by DanielRuf** [comment]
In general this is an issue with node-gyp I guess. Nothing that we can track or fix in this case here.

**Comment by sashabeep** [comment]
@DanielRuf That's pity, i think i will try this on VM with other OS later. Waiting for new version and online customizer wake-up. Using simple template with foundation-cli or "download everything" on the site i cannot uncheck various js plugins i didn't use, and ZURB template is too complicated for me at this point

**Comment by jhwinter** [comment]
If you're having issues even after doing `xcode-select --install`, try `sudo xcode-select --reset`. Check the path variable before and after with `xcode-select -print-path` to make sure that it updates properly.

**Comment by meanmachin3** [comment]
I can confirm too. Tried `sudo xcode-select --reset` and `xcode-select --install`. Doesn't seem to be working

```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/meanmachin3/github/meanmachin3.github.io/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/12.10.0/bin/node" "/Users/meanmachin3/github/meanmachin3.github.io/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/meanmachin3/github/meanmachin3.github.io/node_modules/node-sass
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by DanielRuf** [comment]
Please see https://github.com/nodejs/node-gyp/issues/1861, https://github.com/nodejs/node-gyp/issues/1927 and the other issues and report this at node-gyp.

This is nothing that we can handle or fix as I already wrote and our issue tracker is not the right place for this thirdparty dependency which is part of NodeJS =)

**Comment by DanielRuf** [comment]
And also https://github.com/nodejs/node-gyp/issues/1861#issuecomment-543022396 for some steps which you can try.

**Comment by maxcbc** [comment]
You might need to open Xcode, then in the menu go to
`Xcode > Preferences > Locations > Command Line Tools`
 and then select a version.
This fixed it for me

**Comment by avega04** [comment]
Removing and reinstalling the command line tools does the trick: 
1. `sudo rm -rf $(xcode-select -print-path)`  # Enter root password.  No output is normal.
2. `xcode-select --install`

(From https://github.com/nodejs/node-gyp/pull/1940/files)

**Comment by mdoghri** [comment]
> You might need to open Xcode, then in the menu go to
> `Xcode > Preferences > Locations > Command Line Tools`
> and then select a version.
> This fixed it for me

Worked for me as well. Thanks!

**Comment by mlx-martin** [comment]
> Removing and reinstalling the command line tools does the trick:
> 
> 1. `sudo rm -rf $(xcode-select -print-path)`  # Enter root password.  No output is normal.
> 2. `xcode-select --install`
> 
> (From https://github.com/nodejs/node-gyp/pull/1940/files)

This worked for me, Thank you

**Comment by sashabeep** [comment]
@mlx-martin in my case still getting those errors, so i'll leave it for now
```
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/sashabeep/node-foundation-customizer/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/sashabeep/node-foundation-customizer/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/sashabeep/node-foundation-customizer/node_modules/node-sass
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by DanielRuf** [comment]
```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
```

There is some error above this.

**Comment by dgonch5** [comment]
> Removing and reinstalling the command line tools does the trick:
> 
> 1. `sudo rm -rf $(xcode-select -print-path)`  # Enter root password.  No output is normal.
> 2. `xcode-select --install`
> 
> (From https://github.com/nodejs/node-gyp/pull/1940/files)

Worked for me! Thank you.

**Comment by DanielRuf** [comment]
I'm locking this issue as it should be resolved and comments like "I have this too" and "thanks it works now" do not contribute any new things. This sends a notification to everyone in this issue.

Please use the linked node-gyp issue if you still face this problem.

Closing as resolved.
